Add `calculate` and `operate` modules
Bluette1/calculator pull request #5
Opened 2020-12-01 12:55 UTC by Bluette1

#####  Add `calculate` and `operate` modules - milestone 4
- Create a new logic folder inside src and initialize two javascript files there: `calculate.js` and `operate.js`.

- Add the big.js package to your project dependencies.
- Implement the calculate.js module with one default method: calculate.
  - `calculate` should accept a calculator data object and a button name as arguments.
       - The calculator data object should contain three properties: `total`, `next `, and `operation`.

-  should use the `buttonName` argument to mutate the calculator’s data object and return its modified version. For instance, if `buttonName` == "+/-", it should multiply total and next by -1 to make it negative or positive.

- Implement the operate.js module with one default method: operate
   -  import the big.js module from the corresponding npm package.
`operate` should accept `numberOne`, `numberTwo`, and `operation` as arguments.
Using the value of the operation argument, this method should perform a simple math operation. For instance, if operation == "-", it should return the result of subtracting the two passed numbers. 
  - Wrap the numbers with `big.js` classes so you can operate on big numbers.
 - Is called by `calculate`.js should be used to calculate the `total` property, using `buttonName`.

2020-12-01 16:07 UTC, MuriloRoque requested changes
## Status: Changes requested :red_circle: 

### Hello @Bluette1 :wave: 

### This milestone is working great, you did an amazing job :clap: 

### There's only one small detail to fix before moving forward, please check my comment in your code below.

Kindly make the requested changes and submit for another review, please :pray: 

I will be on Slack 24/7 in case you have any questions about this review :handshake: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2020-12-01 16:07 UTC, MuriloRoque commented on src/logic/operate.js
> +  return firstNum.div(secondNum).times(100);
- [ ] Instead of using `div` here, try using the [`mod`](http://mikemcl.github.io/big.js/#mod) function from `Big.js` module to work with percentages.

2020-12-01 16:33 UTC, Bluette1 commented on src/logic/operate.js
> +  return firstNum.div(secondNum).times(100);
@muriloroque: Okay, thank you very much for the review!

2020-12-01 17:08 UTC, bellom approved these changes
## Hi @Bluette1  :clap: 

**Great work making all the necessary corrections from the previous review.**

# Status: Approved 👍 

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit the project completion form.
Good luck in the next milestone :slightly_smiling_face:_ 

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_*

2020-12-02 10:17 UTC, Bluette1 commented
@bellom, thank you very much for the review!

2020-12-02 10:17 UTC, merged